export interface IPerson{
    PersonCd:string
    PersonName:string
    PersonNameKana:string
    Birthday:string
    Sex:string
    Zip:string
    Address1:string
    Address2:string
    Address3:string
    Address4:string
    Tel:string
    Mobile:string
    MailAddress:string
    AuthenticationDate:string
    DeleteFlag:string
    CreateUser:string
    CreateDate:string
    UpdateUser:string
    UpdateDate:string
}